### ISSUE TITLE
Version of singult.jar not in any public repo

### ISSUE THREAD

**Issue by thegeez** [lynaghk/c2-demos#1]
singult:jar:0.1.2-SNAPSHOT is not on clojars or any other standard lein repo (only singult 0.1.1 is). This is a dependency through c2 "0.2.0-SNAPSHOT" for the todoMVC demo.

I used singult "0.1.1" and that seemed to work fine:
In project.clj:
[com.keminglabs/c2 "0.2.0-SNAPSHOT" :exclusions [com.keminglabs/singult]]
[com.keminglabs/singult "0.1.1"]

**Comment by lynaghk** [comment]
Yep, I got an email about this and pushed Singult earlier this morning:

```
https://clojars.org/com.keminglabs/singult/versions/0.1.2-SNAPSHOT
```

Please reopen if you try again and it doesn't work.
